"""
Django settings for myla_survey project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'v2nne37ag_rvp^psn2$z@mftp=m^acq#b!%ndaksd5+=3cg)z6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# This is required by flatpages flow. For Example Copyright information in the footer populated from flatpages
SITE_ID = 1

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',
    'material',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myla_survey.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "myla_survey/templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myla_survey.wsgi.application'

# Databases

DATABASES = {}

DATABASES['default'] = {
    'ENGINE': config('DJANGO_DB_ENGINE', default='django.db.backends.mysql'),
    'NAME': config('DJANGO_DB_NAME', default='myla_survey'),
    'USER': config('DJANGO_DB_USER', default='myla_survey_user'),
    'PASSWORD': config('DJANGO_DB_PASSWORD', default='myla_survey_pw'),
    'HOST': config('DJANGO_DB_HOST', default='myla_survey_mysql'),
    'PORT': config('DJANGO_DB_PORT', default=3306),
}

DATABASES['qualtrics'] = {
    'ENGINE': config('QUALTRICS_DB_ENGINE', default='django.db.backends.mysql'),
    'NAME': config('QUALTRICS_DB_NAME', default=''),
    'USER': config('QUALTRICS_DB_USER', default=''),
    'PASSWORD': config('QUALTRICS_DB_PASSWORD', default=''),
    'HOST': config('QUALTRICS_DB_HOST', default=''),
    'PORT': config('QUALTRICS_DB_PORT', default=3306),
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

PROJECT_ROOT = os.path.abspath(
    os.path.dirname(__file__)
)

STATIC_ROOT = os.path.join(PROJECT_ROOT, 'static')

STATIC_URL = '/static/'

# upon successful login
LOGIN_REDIRECT_URL = '/'
